### ISSUE TITLE
Unable to create new item

### ISSUE THREAD

**Issue by DuneganS** [adamk33n3r/crafting-calculator#1]
When attempting to create a new item I am unable to enter anything into the "Icon" field as its readonly. This results in me not being able to click the "Save" button which is disabled. Is this the intended behavior? Am I missing something trivial?
 
![msedge_DtKHnNoIW4](https://user-images.githubusercontent.com/22308246/95919602-e2ac1900-0d7b-11eb-80bf-a5cf4f71fe7f.png)

**Comment by adamk33n3r** [comment]
As the placeholder text says, you just click the input and paste an image from your clipboard. The input itself is "disabled" so that you can't type into it. Pasting the image has special code that will convert the image data into a base64 string that will show up in the input.

For example, go to https://minecraft.fandom.com/wiki/Redstone and right click the image of the redstone dust and click "Copy image". Then go back to the calculator and click on the Icon input and press ctrl-v to paste.

**Comment by DuneganS** [comment]
Thanks for the quick reply. I attempted that earlier with no luck but it seems fine now.

**Comment by adamk33n3r** [comment]
I apologize for any confusion! But I am happy to see that it is getting use :)
